# Generated by Django 5.0.4 on 2024-04-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='preco',
            field=models.FloatField(),
        ),
    ]
